########################################################
# IMÁGENES PLACEHOLDER — AUTOGENERADAS
# ------------------------------------------------------
# Fondos y sprites de color sólido con el nombre escrito,
# generados para que el capítulo sea ejecutable de punta
# a punta sin arte final. Reemplazar cada 'image' por el
# asset real cuando esté disponible, manteniendo el mismo
# nombre para no romper referencias en el guion.
########################################################

# ---- FONDOS ----
image bg aldea_incendio = "bg/bg aldea_incendio.png"
image bg biblioteca_publica_ciudad = "bg/bg biblioteca_publica_ciudad.png"
image bg biblioteca_templo = "bg/bg biblioteca_templo.png"
image bg bosque_entrada = "bg/bg bosque_entrada.png"
image bg bosque_entrada day = "bg/bg bosque_entrada day.png"
image bg bosque_noche_persecucion = "bg/bg bosque_noche_persecucion.png"
image bg cabana_bruja_exterior = "bg/bg cabana_bruja_exterior.png"
image bg cabana_bruja_interior = "bg/bg cabana_bruja_interior.png"
image bg cabana_bruja_interior night = "bg/bg cabana_bruja_interior night.png"
image bg callejon_ciudad = "bg/bg callejon_ciudad.png"
image bg ciudad_incendio = "bg/bg ciudad_incendio.png"
image bg ciudad_plaza = "bg/bg ciudad_plaza.png"
image bg ciudad_plaza night = "bg/bg ciudad_plaza night.png"
image bg ciudad_puerta_dia = "bg/bg ciudad_puerta_dia.png"
image bg ciudad_puerta_noche_escape = "bg/bg ciudad_puerta_noche_escape.png"
image bg claro_entrenamiento = "bg/bg claro_entrenamiento.png"
image bg claro_ruinas_antiguas = "bg/bg claro_ruinas_antiguas.png"
image bg coliseo_ciudad = "bg/bg coliseo_ciudad.png"
image bg combate_generico = "bg/bg combate_generico.png"
image bg cueva_entrada = "bg/bg cueva_entrada.png"
image bg cueva_interior = "bg/bg cueva_interior.png"
image bg enfermeria_templo = "bg/bg enfermeria_templo.png"
image bg escuela_pueblo = "bg/bg escuela_pueblo.png"
image bg gremio_aventureros_interior = "bg/bg gremio_aventureros_interior.png"
image bg herreria_ciudad = "bg/bg herreria_ciudad.png"
image bg herreria_interior = "bg/bg herreria_interior.png"
image bg herreria_interior night = "bg/bg herreria_interior night.png"
image bg iglesia_pueblo = "bg/bg iglesia_pueblo.png"
image bg muralla_ciudad = "bg/bg muralla_ciudad.png"
image bg muralla_ciudad night = "bg/bg muralla_ciudad night.png"
image bg pantalla_derrota = "bg/bg pantalla_derrota.png"
image bg posada_pueblo night = "bg/bg posada_pueblo night.png"
image bg pueblo_dia = "bg/bg pueblo_dia.png"
image bg puente_colgante_bosque = "bg/bg puente_colgante_bosque.png"
image bg taberna_ciudad = "bg/bg taberna_ciudad.png"
image bg taberna_ciudad night = "bg/bg taberna_ciudad night.png"
image bg templo_refugio = "bg/bg templo_refugio.png"

# ---- PERSONAJES ----
image amigo1 = "characters/amigo1.png"
image amigo2 = "characters/amigo2.png"
image bruja_arpia = "characters/bruja_arpia.png"
image bruja_personaje = "characters/bruja_personaje.png"
image director_escuela = "characters/director_escuela.png"
image doran = "characters/doran.png"
image elyra_personaje = "characters/elyra_personaje.png"
image fanatico1 = "characters/fanatico1.png"
image gorrak = "characters/gorrak.png"
image guardia_npc = "characters/guardia_npc.png"
image lyanwe = "characters/lyanwe.png"
image maestro_occam = "characters/maestro_occam.png"
image mira = "characters/mira.png"
image padre_herrero = "characters/padre_herrero.png"
image pueblerino_asustado = "characters/pueblerino_asustado.png"
image sable_personaje = "characters/sable_personaje.png"
image sacerdote_iglesia = "characters/sacerdote_iglesia.png"
image soldado1 = "characters/soldado1.png"
image theron = "characters/theron.png"
image theron_personaje = "characters/theron_personaje.png"
image thrain = "characters/thrain.png"
image viajero_misterioso = "characters/viajero_misterioso.png"
image wren = "characters/wren.png"
image wren_personaje = "characters/wren_personaje.png"
